### Login
POST http://127.0.0.1:8000/api/v1/auth/login
Accept: application/json
Content-Type: application/json

{
    "email": "admin@mail.com",
    "password": "admin54321"
}

### registro

### perfil
GET http://127.0.0.1:8000/api/v1/auth/perfil
Accept: application/json
Authorization: Bearer 3|wxZuVkB5avB6mTbTZrUqmRMGvxSJuuZjnCuUtCSW

### logout
POST http://127.0.0.1:8000/api/v1/auth/logout
Accept: application/json
Authorization: Bearer 4|zNRxs9XDFyNnTWBX8pdWR2TKsFb3p8mbxDzp8Aa9
